- app/src/components/elements/DashboardItem/index.tsx
- app/src/components/elements/DashboardItemContainer/index.tsx
- app/src/components/elements/DashboardRow/Desktop/index.tsx
- app/src/components/elements/DashboardRow/Mobile/index.tsx
- app/src/components/elements/NavBar/Mobile/index.tsx
- app/src/components/layouts/MainLayout.tsx
- app/src/pages/Home.tsx
- app/src/pages/hooks/dashboardContents.ts
- app/src/pages/hooks/useHomePage.ts
- app/src/utils/types/Dashboard.d.ts
page에 많던 DashboardRow, DashboardItem들을 map을 이용하여 줄이는 방식을 생각해봤습니다. 
Chart는 아직 추가해보지 못햇지만 @lev-Zero 님과의 협업을 위해 일단 중간 과정에서 올립니다. 
커밋 보실 때 헷갈릴만한 것 하나 공유드립니다. 
기존 DashboardItem -> DashboardItemContainer로 명칭 변경, DashboardItemContainer에는 rowSpan, colSpan 등 기본 Grid 속성만 들어있음. 
DashboardItem에 제목, 세부 설명 및 Element(이후 차트가 들어갈 부분)을 인자로 받도록 되어있습니다. 
DashboardItem.tsx를 보실 때 수정된 게 아니라 새로 생긴 파일임을 염두하시고 보면 이해하실 수 있을 것 같아요
> feat: :sparkles: DashboardItem 추상화 방식 제시

- app/src/components/common/Label.tsx
- app/src/components/elements/Footer/AboveTabletFooter.tsx
- app/src/components/elements/Footer/MobileFooter.tsx
- app/src/components/elements/UserSearchBar/AboveTabletUserSearchBar.tsx
- app/src/components/elements/UserSearchBar/UserSearchModal.tsx
- app/src/pages/EvalLogSearchPage/EvalLogItem.tsx
- app/src/pages/ProjectPage/ProjectPage.tsx
- app/src/styles/global.tsx
ProjectPage 디자인을 변경해보았습니다.
- ProjectPage 디자인 변경
- 이전 디자인에서 추가로 필요한 데이터 : `keywords`, `skills`, `description` (백엔드와 상의 완료)
- 이전 디자인으로부터의 변경점
1. 차트가 평가 당 점수(101 ~ / 80 ~ 100 / 0 ~ 79점)이 아닌 팀 당 Pass / Fail 비율로 변경되었습니다. 
2. 기존 `C`, `Makefile` 처럼 더 직관적인 라벨을 커스텀으로 달려고 했으나 모든 과제에 대하여 제작해야 하기도 하고, `keywords`와 `skills`가 제 생각보다 더 상세하게 잘 와서 그냥 사용하기로 했습니다. 
3. 기존 `description` 대신 한글로 짧게 과제마다 적으려고 했으나 2의 이유와 동일한 이유로 `description`으로 그냥 사용하기로 했습니다.
- 자잘한 스타일링 (Label 패딩 수정)
- 자잘한 리팩토링 (global.tsx에 strong 태그 굵게 만드는 CSS Selector 추가) : 기존 방식으로는 텍스트를 드래그했을 때 끊기는 부분이 있었음.
> 💄 [Feature] ProjectPage 디자인 변경

- app/src/components/elements/PageBtnList/PageBtn.tsx
- app/src/components/elements/PageBtnList/index.tsx
- app/src/components/templates/LeaderBoard/LeaderBoard.tsx
- app/src/components/templates/LeaderBoard/LeaderBoardItem.tsx
- app/src/pages/LeaderBoardPage/tabs/LeaderboardCoalitionScoreTab.tsx
- app/src/pages/LeaderBoardPage/tabs/LeaderboardCoalitionScoreTabResult.tsx
- app/src/pages/LeaderBoardPage/tabs/LeaderboardEvalCountTab.tsx
- app/src/pages/LeaderBoardPage/tabs/LeaderboardEvalCountTabResult.tsx
- app/src/pages/LeaderBoardPage/tabs/LeaderboardExpIncrementTab.tsx
- app/src/pages/LeaderBoardPage/tabs/LeaderboardExpIncrementTabResult.tsx
- app/src/pages/LeaderBoardPage/tabs/LeaderboardLevelTab.tsx
- app/src/pages/LeaderBoardPage/tabs/LeaderboardLevelTabResult.tsx
- app/src/pages/PageSkeletons/LeaderBoardTabResultSkeleton.tsx
- app/src/providers/ApolloProvider.tsx
- 리더보드 누적, 코알리숑 스코어 BE 오류 빼고 제작 완료
- Leaderboard 주간 / 월간 연동
- 자기인 경우 색 다르게
- 페이지 누르면 이동하게
- close #68
> ✨ [Feature] 리더보드 페이지 주간/월간, 페이지 버튼, 자기일 때 색 변화

- app/src/Profile/dashboard-contents/General/TeamInfo/TeamInfoTable.tsx
jiychoi
- text-overflow: ellipsis 써서 overflow일 때 `...` 표시하고 싶었는데 잘 안돼서 일단 넘깁니다. 
jkong
- close #122
> 🐛 fix: TeamInfoTable 글자의 너비가 클 때 발생하는 버그

- app/vite.config.ts
#171 에서 Chrome과 달리 Safari에서 로그인이 작동하지 않는 버그가 있었습니다. 
확인 결과 https://localhost:8080 -> http://localhost/graphql 로 요청을 보내는 과정에서 http <-> https 차이가 있어 발생하는 문제였습니다. 
dev일 때는 http, production일 때는 https로 작동하는 방식으로 변경하였습니다. 
- close #171
> 🐛 [BugFix] localhost https -> http (백엔드 localhost와 호환)

- app/src/@core/providers/ScrollToTop.tsx
- app/src/@shared/components/Pagination/index.tsx
- app/src/Leaderboard/tabs/CoalitionScore/index.tsx
- app/src/Leaderboard/tabs/EvalCount/index.tsx
- app/src/Leaderboard/tabs/ExpIncrement/index.tsx
- app/src/Leaderboard/tabs/Level/index.tsx
- app/src/Leaderboard/utils/parseDateTemplate.ts
- app/src/Leaderboard/utils/parsePageNumber.ts
- `http://localhost:8080/leaderboard/level?dateTemplate=total&pageNumber=1` 형식으로 변경되었습니다. 
- scrollToTop 동작에 queryString 변화 조건을 추가하였습니다. 
- close #190 
- close #105
> 🐛 fix: 리더보드 dateTemplate, pageNumber 변경시 queryString

- app/src/@shared/components/Chart/DonutChart.tsx
- app/src/@shared/components/Chart/LineChart.tsx
- app/src/@shared/components/Chart/PieChart.tsx
- app/src/@shared/components/Chart/options/defaultOptions.ts
- app/src/@shared/components/DashboardContentView/Rank/RankListItem.tsx
- app/src/@shared/constants/BREAKPOINT.ts
- app/src/@shared/utils/facepaint/mq.ts
- app/src/@shared/utils/formatters/index.ts
- app/src/@shared/utils/formatters/kiloFormatter.ts
- app/src/@shared/utils/formatters/millionFormatter.ts
- app/src/@shared/utils/react-responsive/useDeviceType.ts
- app/src/EvalLogSearch/components/FlagLabel/index.tsx
- app/src/Home/dashboard-contents/Coalition/MonthlyTigCountPerCoalition.tsx
- app/src/Home/dashboard-contents/Coalition/ScoreRecordsPerCoalition.tsx
- app/src/Home/dashboard-contents/Coalition/TotalScoresPerCoalition.tsx
- app/src/Home/dashboard-contents/Team/RecentExamResult.tsx
- app/src/Home/dashboard-contents/User/AliveUserCountRecords.tsx
- app/src/Home/dashboard-contents/User/AverageDurationPerCircle.tsx
- app/src/Home/dashboard-contents/User/BlackholedCountPerCircle.tsx
- app/src/Home/dashboard-contents/User/BlackholedRate.tsx
- app/src/Home/dashboard-contents/User/MemberRate.tsx
- app/src/Home/dashboard-contents/User/UserCountPerLevel.tsx
- app/src/Leaderboard/components/Leaderboard/LeaderboardListItem.tsx
- app/src/Profile/dashboard-contents/General/BeginAt.tsx
- app/src/Profile/dashboard-contents/General/LevelRecords.tsx
- app/src/Profile/dashboard-contents/General/TeamInfo/DateDiffWithStatus.tsx
- app/src/Profile/dashboard-contents/Versus/LevelRecords.tsx
- app/src/Profile/dashboard-frames/profileGeneralTabDashboardRows.ts
- app/src/Profile/utils/padWithNullValues.ts
- app/src/Project/dashboard-contents/ValidatedRate.tsx
차트 가독성을 높였습니다. 
> 기존이 왼쪽, 수정이 오른쪽입니다. 
- 차트 전체에 적용되는 폰트를 Pretendard로 변경하였습니다. PieChart에서 변화가 가장 두드러집니다.  
- 이 카드와 같이 datetime 류 차트에 대하여, `xlabel` 싱크가 도저히 안 맞아서 제거하였습니다. 
- 호버 시 아래 라벨 비슷하게 역할을 해주니까 이상하진 않다고 생각했습니다. 
- LineChart의 선을 굵게하고, smooth로 변경하여 가독성을 높였습니다. 
- 위 카드와 동일하게 datetime 류 차트이므로 `xlabel`을 제거하였습니다. 
- 데이터 전체의 최소/최대값을 계산하여 min, max range를 조정하기 때문에 값 변화에 유동적으로 대응할 수 있습니다.  
- #188 에서 제기되었던 이슈로, 최소값을 50%로 위치하도록 min 값을 조정하였습니다. 
- 위에 표시되는 dataLabel이 잘 나오도록 max를 조정하였습니다. 위 카드와 동일하게 min, max 계산 과정에 데이터의 최소/최대값을 파악하는 로직이 들어가 있어 값 변화에 유동적으로 대응할 수 있습니다. 
- #158 문제를 우회적으로 해결하는 방법을 찾아서 2년 이하 유저의 경우 뒤 쪽을 비우는 뷰를 다시 살렸습니다. 
- 오래 한 유저에 대해서는 [0...24] 개월차 정보가 모두 주어지지만, 아직 2년 정보가 다 주어지지 않은 경우 데이터 뒤에 `{ x: 13, y: null }`의 형식으로 x: 24까지 추가하는 방식으로 추가해줍니다. 이후 차트에서 null 값인 경우 '미정' 문자열을 표시하는 방식으로 …
> 💄[Design] 차트 가독성 제고

- app/src/@shared/components/Chart/HorizontalBarChart.tsx
- app/src/@shared/components/Chart/options/defaultOptions.ts
- app/src/@shared/components/DashboardContent.tsx
- app/src/@shared/components/DashboardContentView/Error/DashboardContentBadRequest.tsx
- app/src/@shared/components/DashboardContentView/Error/DashboardContentLoading.tsx
- app/src/@shared/components/DashboardContentView/Error/DashboardContentNotFound.tsx
- app/src/Home/dashboard-contents/Coalition/ScoreRecordsPerCoalition.tsx
- app/src/Home/dashboard-contents/Coalition/TotalScoresPerCoalition.tsx
- app/src/Home/dashboard-contents/Team/RecentExamResult.tsx
- app/src/Home/dashboard-contents/User/AliveUserCountRecords.tsx
- app/src/Home/dashboard-contents/User/AverageDurationPerCircle.tsx
- app/src/Home/dashboard-contents/User/BlackholedCountPerCircle.tsx
- app/src/Home/dashboard-contents/User/BlackholedRate.tsx
- app/src/Home/dashboard-contents/User/MemberRate.tsx
- app/src/Home/dashboard-contents/User/UserCountPerLevel.tsx
- app/src/Profile/dashboard-contents/Eval/RecentComment.tsx
- app/src/Profile/dashboard-contents/General/LevelRecords.tsx
- app/src/Profile/dashboard-contents/Versus/LevelRecords.tsx
- app/src/Profile/dashboard-contents/Versus/Rankings.tsx
- #205
dataLabel xoffset을 줄이는 방식으로 해결
---
- #206 
DashboardContent에서 title은 있으나 description이 없는 경우에는 공백(&nbsp;)를 추가하여 정렬을 맞춤.   
(selection 하면 공백이 드래그되는게 조금 불편하긴 한데, 1.8rem보다 직관적인 것 같아 그렇게 작성하였습니다.)
---
- #207
해결 방법은 못 찾았지만, #206을 해결하면서 DashboardContent 높이가 낮아지면서 문제가 어느정도 나아졌습니다. 
---
- #213
DashboardContent에 type으로 'Default' | 'ApexCharts' | 'Scrollable'을 받게 하여 title, description 정보의 원천을 하나로 통일했습니다. 
---
- 추가로, 예전에 legend hover, click 시 효과를 없앴었는데, 굳이 없앨 필요가 없어서 되살렸습니다. 
- close #205 
- close #206
- close #207 
- close #213
> 💄 [Design] 대시보드 카드 description 정렬 등

- app/src/Leaderboard/components/Leaderboard/index.tsx
- app/src/Leaderboard/tabs/CoalitionScore/LeaderboardCoalitionScoreTabResult.tsx
- app/src/Leaderboard/tabs/EvalCount/LeaderboardEvalCountTabResult.tsx
- app/src/Leaderboard/tabs/ExpIncrement/LeaderboardExpIncrementTabResult.tsx
- app/src/Leaderboard/tabs/Level/LeaderboardLevelTabResult.tsx
- app/src/Leaderboard/tabs/Level/index.tsx
레벨 탭의 Segmented Control은 누적 밖에 없어서 삭제했습니다.
> ✨ [Feature] 리더보드 집계기간

- app/src/EvalLogSearch/index.tsx
EvalLogSearchTitle 의 totalCount 가 query 의 error 나 loading 상태를 반영하도록 수정
애초에 백엔드에서 같은 상황에 다른 결과를 반환하여 생기는 문제라고 판단하여,
백엔드 api 도 현재는 둘 다 빈 배열을 반환하도록 수정된 상태 입니다.
단, 어떤 이유로든 에러는 발생할 가능성이 있기 때문에, 이를 반영하는 로직도 추가하는 것이 옳다고 판단했습니다.
EvalLogSerach/index.tsx 에 `caclulateTotalCount` 함수 추가,
해당 함수는 query 의 결과를 받아서 number | undefined 를 반환하도록 했습니다.
- close #201
> 🐛  fix: EvalLogSearchTitle 의 totalCount 가 query 의 error 나 loading 상태를 반영하도록 수정

- app/src/@core/components/NavBar/Desktop/index.tsx
> 🐛 fix: 내부에서 로고 클릭 시 /home으로 라우팅

- app/src/@core/components/Modal/ReLoginDialog.tsx
- app/src/@core/components/Spotlight/index.tsx
- app/src/@core/providers/ModalProvider.tsx
ModalProvider에서 전역 모달을 관리하는 것은 동일. 
하지만, 전역 모달의 경우 close 되었을 때 unmount가 되어야 함. (아래 ModalProvider.tsx의 변경점 참고)
background에서 계속 keydown을 listening 하고 있는 버그가 있었음. 
`Mac + K` 버튼으로 Spotlight를 활성화할 수 있습니다.
하지만 기존 ModalProvider의 방식은 open & close 가 mount & unmount를 불러오지 않습니다. 
전역 모달은 App mount 시에 함께 mount 되며, open & close 는 mount & unmount에 영향을 주지 않았습니다. 
일례로, Spotlight를 끄고 페이지를 움직이지 않은 채 다시 켜면 예전 검색어가 남아있었습니다. 
그것을 나름의 기능이라 생각하고 넘겼었는데, 이번 #199 이슈를 살펴보면서 Spotlight의 ArrowUp, ArrowDown 이 close 상태에도  listening 하고 있는 것이 원인임을 발견하였습니다. 
더하여, Spotlight에서 검색한 이후 Spotlight를 끄고 ArrowUp, ArrowDown을 누르면 Spotlight의 Focus가 움직여버리는 버그가 있다는 사실을 알게 되었습니다. 
따라서 기존 @jpham005 님과 얘기를 나눈 방식대로, close 시 전역 모달을 unmount 시키는 방식으로 로직을 변경하게 되었습니다. 
- close #199
> 🐛 fix: 전역 모달을 close 시 unmount

- app/src/Profile/dashboard-contents/General/LevelRecords.tsx
- app/src/Profile/dashboard-contents/Versus/LevelRecords.tsx
min, max 값을 제거하여 해결
- https://github.com/apexcharts/apexcharts.js/issues/1695#issuecomment-661359147
- numeric 타입을 추가하여 해결
ApexCharts는 Safari에 취약합니다... 주의하시길 😭
- close #196
> 🐛 fix: Safari 레벨 증가 그래프 undefined

- app/src/EvalLogSearch/components/EvalLogSearchAbsoluteButton.tsx
- app/src/EvalLogSearch/components/EvalLogSearchDialog.tsx
> 🐛 fix: Safari EvalLogSearchDialog width

- app/src/@shared/components/Chart/LineChart.tsx
- app/src/@shared/components/DashboardContentView/Number/NumberVersus.tsx
line chart, curve smooth 일 때 발생하는 에러인 것 같고 ApexCharts 이슈에도 올라가있긴 한데, 아직 안 고쳐진 듯함. 
100%로 발생하는 것도 아니라서 애매함. 간헐적으로 발생함. 
현재 할 수 있는 것으로는 line chart curve smooth를 풀거나, 애니메이션을 비활성화하는 방법 둘 중에 하나를 택해야 하는데, 
일단 애니메이션 비활성화를 택함. 
- close #239
> 🐛 fix: line chart smooth 일 때 animation glitch

- app/src/@core/layouts/LandingLayout/index.tsx
- app/src/@core/styles/Theme.d.ts
- app/src/@core/styles/defaultTheme.tsx
- app/src/Home/components/Hero/index.tsx
- #195 는 아마 background image timeout 때문에 발생하는 문제로 보입니다. 
- 우주 배경이 사용되는 LandingPage, Hero에 대하여 fallback color를 지정해주었습니다. 
- close #195
> 🐛 fix: Hero background image fallback

- app/src/@core/components/NavBar/Desktop/DesktopNavItem.tsx
- app/src/@core/components/NavBar/Tablet/TabletNavItem.tsx
- app/src/@shared/ui-kit/Tab/Tab.tsx
- app/src/Leaderboard/components/Leaderboard/LeaderboardListItem.tsx
아래 이슈에 더하여, navigate -> link 사용으로 바뀌었지만 내부 layout에 tabIndex가 여전히 설정되어 있어 tab키로 움직일 때에는 동일 요소를 두번 focus 하는 버그가 있어서 tabIndex를 삭제하였습니다. 
- close #251
> 🐛 fix: Layout 밖으로 Link를 뺐을 때 :focus가 적용되지 않음

- app/src/Home/dashboard-contents/Team/RecentExamResult.tsx
GET_RECENT_EXAM_RESULT query 를 기존에 variables 를 제공하지 않고 있었는데,
257b0cd 에서 variables 를 추가하면서 마지막에서 두번째 시험이 반환되는 문제가 있었습니다.
이를 제거하여 다시 가장 최근 시험 결과를 반환 받고자 합니다.
모호한 variable key 이름으로 인해 생긴 문제라고 봅니다.
이후 백엔드에서 이름을 수정할 예정 입니다.
> :bug: fix: GET_RECENT_TEAM_RESULT query 에 불필요한 인자를 제공하던 문제 수정

- app/src/Team/index.tsx
> fix(design): 팀 페이지 평가기록 짧을 때도 채워지도록 수정

- app/src/Profile/dashboard-contents/General/LevelRecords.tsx
- app/src/Profile/dashboard-contents/Versus/LevelRecords.tsx
> fix(Chart): 레벨 증가 그래프 모든 legend 껐을 때 x축 수치 달라짐

- app/src/Profile/dashboard-contents/Versus/DayFromBeginAt.tsx
음수로 표현하는 것은 UI 상 좋지 않아보이지만, 마땅히 생각나는 대체 문구가 없어서 일단 두었습니다.  
추후 develop 브랜치에서 **아직 들어오지 않은 신규 유저에 대한 고려**를 별도 이슈로 올리겠습니다. 
- fix #294
> fix(versus): 본과정 시작 전 유저에 대한 "본과정 시작한지" 카드 오류

- app/src/@core/components/Spotlight/index.tsx
- app/src/EvalLogSearch/components/EvalLogSearchDialog.tsx
- app/src/EvalLogSearch/utils/trimEvalLogSearchForm.ts
- Spotlight의 input trim
- EvalLogSearchForm의 input trim
- 구글 검색도 동일 로직으로 작동합니다. (공백 포함 입력 시 trim 되어 쿼리 진행)
- close #252
> [Feature] Trim input

- app/src/Calculator/atoms/subjectListAtom.ts
- app/src/Calculator/components/CalculatorInput/CalculatorInputHeader.tsx
- app/src/Calculator/components/ProjectSpotlight/index.tsx
- app/src/Calculator/hooks/useSubjectList.ts
- rebase하면서 적용되지 않은 커밋들 반영
- blackhole 계산식
- 과제 추가시 focus이동
- 과제 목록 4개 -> 5개
- close #314
> [Fix] Calculator rebase error 수정

- app/src/@core/components/Spotlight/index.tsx
Searchbar enter검색시 정확도 향상
search debounce 250 -> 50으로 수정
여러가지 방안(debounce 0으로 수정, query 다시 불러오기 등)을 고려했으나
검색 페이지를 따로 만드는게 맞다고 생각들어 debounce만 수정했습니다.
검색 페이지는 이슈로 따로 만들어놓을게요!
- closed #262
> [Feat] Search debounce 수정

- app/src/Calculator/components/CalculatorBasicInfoInputGroup/index.tsx
- app/src/Calculator/components/CalculatorInputContentCardView/CalculatorInputContentCardListItem.tsx
- app/src/Calculator/components/CalculatorInputContentTableView/index.tsx
calculator input type=number 일 때 value가 0에서 다른 숫자로 바뀌면 앞에 0이 남아있는 현상 해결
input의 value를 string으로 변경
> [Feat] leadingZero 현상 수정

- app/src/@shared/components/LoginButton/FtLoginButton.tsx
- app/src/@shared/components/LoginButton/LoginButton.tsx
Bad Request로 비정상 로그아웃 시 localStorage에 적용되어 있던 `theme_preference: dark` 가 삭제되지 않는 문제가 있었습니다. 
absolute white & black으로 변경하여 해결하였습니다.
> [BugFix] LoginButton absolute white로 변경

- app/src/@shared/ui-kit/Clickable/Clickable.tsx
- app/src/@shared/ui-kit/FAB/FAB.tsx
- app/src/@shared/ui-kit/FAB/index.tsx
- app/src/EvalLogSearch/components/EvalLogSearchAbsoluteButton.tsx
- FAB를 추가하였습니다. 
- 평가로그 검색 버튼이 더 눈에 띄게 변경되었습니다. 
Ref. <https://mui.com/material-ui/react-floating-action-button/>
기존
변경
Extended FAB (예시)
- close #331
> [Feat] FAB 추가

- app/src/Profile/dashboard-contents/General/TeamInfo/TeamInfoTable.tsx
In Firefox,
jkong
jiychoi
- firefox에서 td overflow-x 적용 안되는 문제가 있는데, 이유를 못 찾았습니다. 
- `overflow-x: hidden`을 `overflow: hidden`으로 변경하는 방식으로 해결하였습니다. 
- Chrome, Safari에서는 되는데 말이죠...😭
- close #295
- 둘러본 결과 Firefox에서 깨지는 UI가 해당 이슈 제외하고 없는 듯합니다. Project에 있는 **Firefox UI 테스트** 카드를 해당 이슈 종료와 함께 Done으로 옮기고, 앞으로는 Firefox 최신 버전도 Chrome, Safari와 함께 테스트하기로 하였습니다.
> [Fix] Firefox에서 td overflow-x 적용 안됨

- app/src/@core/providers/ApolloProvider.tsx
- 기존 안에서는 `error.message`가 그대로 노출되어 UX 상 좋지 않다는 피드백이 있었습니다. 
- 이후 Backend 400 반환 시 Code가 분기되면, 그에 상응하는 body text를 다시 변경할 예정입니다. 
- close #330
> [Fix] ReLoginDialog body 텍스트 고정

- app/src/Profile/dashboard-contents/Eval/DestinyRanking.tsx
- app/src/Profile/dashboard-contents/Eval/RecentComment.tsx
- app/src/Profile/dashboard-contents/General/TeamInfo/index.tsx
- app/src/Project/dashboard-contents/ValidatedRate.tsx
- app/src/Team/index.tsx
최근 쓴 코멘트 없을 때
인연 스코어 없을 때
TeamInfo 표는 적절한 UI가 잘 생각이 나지 않아 일단 보류합니다. 
- close #329
> [Fix] 데이터가 없을 때에 대한 핸들링 (최근 쓴 코멘트, 인연 스코어)

- app/src/@shared/components/LoginButton/GoogleLoginButton.tsx
- app/src/FtOAuthRedirect/index.tsx
- app/src/Setting/sections/AccountSection/DeleteAccountDialog.tsx
- app/src/Setting/sections/LinkGoogleSection/LinkGoogleButton.tsx
sessionStorage에 Google credential을 저장하는 조건은 다음과 같습니다. 
1. FtOAuthRedirect
2. **구글 로그인 버튼**으로 로그인 
해당 조건에서 error 반환 시 `removeGoogleCredential()` 함수를 추가하였습니다. 
버그 발생 상황은 #323 댓글에 적어놓았습니다. 
- close #323
> [Fix] google login error 반환 시 googleCredential 삭제

- app/src/@core/components/Modal/ReLoginDialog.tsx
- app/src/@core/components/Spotlight/index.tsx
근본적인 해결책을 못찾았습니다.
임시로 spotlight, relogindialog 에러를 고쳤어요
- spotlight에서 페이지 이동시 spotlight이 꺼지는 로직을 뺐습니다 -> 언제 쓰이는지 모르겠네요
- reloginDialog에서 navigate 대신 페이지 새로고침을 시켰습니다 -> 이거는 logout쪽도 이런식으로 바꾸려고 생각중이에요 (atom상태 유지되는 현상 때문)
<br />
<br />
이것저것 찾아본 결과 Provider 바깥에 Router로 감싸져 있어야 하는 것 같아요
근데 `<RouterProvider router={router} />` 형태로 만드셔서
바꾸려면 꽤나 작업이 커질 것 같아 임시 작업만 한 상태입니다
나중에 provider에서 useLocation 또는 navigate를 사용하게 되면 고치긴 해야되는 문제로 보입니다 😢
Ref. [참고사이트](https://stackoverflow.com/questions/66747556/react-js-error-uselocation-may-be-used-only-in-the-context-of-a-router-com)
- close #350
> [Fix] spotlight & reloginDialog error

- app/src/@core/AppProvider.tsx
- app/src/@core/appRouter.tsx
- app/src/@core/components/Modal/ReLoginDialog.tsx
- app/src/@core/components/Spotlight/SpotlightListItem.tsx
- app/src/@core/providers/ModalProvider.tsx
그냥 ModalProvider를 router 안으로 옮겼습니다. 
- appRouter.tsx 의 변경사항이 복잡하게 잡혔는데, 그냥 제일 바깥에 ModalProvider로 감싼 것 밖에 변경한게 없으니 참고 바랍니다. 
기존 Spotlight에서 location 변경을 useEffect로 감지하여 바뀌면 Spotlight가 닫히도록 했던 코드를, SpotlightListItem의 Link onClick 시 닫히도록 수정하였습니다. 다시 useEffect 코드를 살리려고 봤는데, 굳이 Spotlight 전체에 useEffect를 걸 필요가 없더라구요. 
- Ref. #346 
- Ref. #352 (해당 PR에서 했던 일을 되돌리고 다른 방식으로 해결한 것이라 보시면 됩니다)
> [Fix] ModalProvider를 router 내부로 이동

- app/src/@core/atoms/calculatorDialogAtom.ts
- app/src/@core/components/Modal/CalculatorDialog.tsx
- app/src/Calculator/components/ProjectSpotlight/Spotlight.tsx
- 이전에 올리셨던 커밋에 빌드 에러가 있길래 확인해보다가 발견하였습니다. 
- **프로젝트 추가 오류**에는 20개 이상의 프로젝트를 추가했을 때, 동일한 프로젝트를 추가했을 때로 description이 두 가지가 나올 수 있는데 기존 올리신 코드에서는 고정되어있어 고쳤습니다. 
@42sungwook 커밋 올리시기 전에 `pnpm build:dev` 해서 빌드 에러가 없는지 확인 후 올려주시기 바랍니다.
> [Fix] (CalculatorDialog) description이 고정되어 있음

- app/src/@shared/components/DashboardContentView/Number/NumberVersus.tsx
- app/src/@shared/types/Coalition.d.ts
- app/src/@shared/types/Promo.d.ts
- app/src/@shared/types/UserProfile.d.ts
- app/src/Profile/components/UserProfile/index.tsx
- app/src/Profile/contexts/MyUserProfileContext.ts
- app/src/Profile/contexts/UserProfileContext.ts
> [Fix] type에 따른 build error

- app/src/@core/components/Header/Mobile/index.tsx
- app/src/@core/components/NavBar/Tablet/index.tsx
- app/src/@core/components/SearchBarShapeButton/index.tsx
- app/src/@core/components/Spotlight/SearchButtonTriggerSpotlight.tsx
- app/src/@core/layouts/MainLayout/index.tsx
기존
수정
검색 버튼이 혼자 붕 떠서 위로 깔끔하게 옮겼습니다.
> [Design] Mobile Spotlight Trigger를 헤더로 올림

- app/src/@core/layouts/MainLayout/mainLayoutGlobalStyle.tsx
- app/src/@core/styles/darkTheme.tsx
- app/src/@core/styles/lightTheme.tsx
- 문제의 원인은 `background-attachment: fixed`와 `background: linear-gradient()`를 동시에 사용한 것이었습니다. 
- 디자인 상 그라디언트 배경이 예쁘긴 하지만, 일단 단일 색으로 수정하였습니다. 
- close #359
> [Fix] background.main.default gradient 삭제

- app/src/@shared/components/Chart/hooks/useDefaultOptions.ts
- app/src/Home/dashboard-contents/Coalition/ScoreRecordsPerCoalition.tsx
- app/src/Home/dashboard-contents/Eval/EvalCountRecords.tsx
- app/src/Home/dashboard-contents/Team/TeamCloseRecords.tsx
- app/src/Home/dashboard-contents/User/AliveUserCountRecords.tsx
- app/src/Home/dashboard-contents/User/BlackholedCountRecords.tsx
- app/src/Profile/dashboard-contents/Eval/CountRecords.tsx
- app/src/Profile/dashboard-contents/LogtimeAndProject/LogtimeRecords.tsx
차트 zoom-inout을 되살렸지만(#364), 무한정 확대/축소가 되어 UX에 좋지 않은 문제가 있었습니다. 
- 일간 지표 : 365일 불러옴, 최근 18일만 초기 표시, 축소 한계는 diff 2일, 확대 한계는 diff가 xrange 안일 때까지만 가능합니다. 
- 월간 지표 : 전체 지표의 경우 42 시작달, 유저의 경우 본과정 시작달로부터의 정보 불러옴, 최근 12개월만 초기 표시, 축소 한계는 diff 2개월, 확대 한계는 diff가 xrange 안일 때까지만 가능합니다. 
- pan 기능을 추가로 되살렸는데, 이건 차트 배율을 조정하지 않고 옆으로 슬라이드할 때 쓰는 겁니다. (하단 영상 참고)
- Ref: [Apex Charts- Limiting Zoom out](https://stackoverflow.com/questions/62815241/apex-charts-limiting-zoom-out)
> [Fix] 기본 배율 지정, 과도한 확대/축소 제한

- app/src/@shared/components/Chart/hooks/useDefaultOptions.ts
- app/src/Home/dashboard-contents/Coalition/ScoreRecordsPerCoalition.tsx
- app/src/Home/dashboard-contents/Eval/EvalCountRecords.tsx
- app/src/Home/dashboard-contents/Team/TeamCloseRecords.tsx
- app/src/Home/dashboard-contents/User/BlackholedCountRecords.tsx
- app/src/Profile/dashboard-contents/Eval/CountRecords.tsx
- app/src/Profile/dashboard-contents/LogtimeAndProject/LogtimeRecords.tsx
> BE에서 '여행 중인 유저 수 추이' 작업 완료된 이후에 해당 사항 수정하여 머지하겠습니다. 
- close #414
> [Fix] Disable toolbar in touch device

- app/src/@shared/ui-kit/Select/SelectTrigger.tsx
- app/src/Profile/dashboard-contents/General/DailyActivities/YearSelect/index.tsx
> **main** 브랜치로 향하는 PR입니다.
360px에 가까운 디바이스에서 잔디 카드의 총점이 4자리 수인 유저의 잔디 카드를 보는 경우 Overflow가 발생하는 것을 확인하였습니다. 
YearSelect(대상 연도를 고르는 Select) 크기를 축소시켰습니다.
> [Hotfix] YearSelect width 줄이기

- app/src/@shared/utils/firstDayInPreviousMonth.ts
- app/src/@shared/utils/injectEmptyMonth.ts
setMonth 관련 미처 생각하지 못했던 오동작이 있어 수정하였습니다. 
현재 날짜(2023.12.30)가 28일 초과라 발생하는 문제입니다. 
- 3월 31일의 한 달 전은 2월 28일이 아니라 Date(2023, 2-1, 31), 2월 31일, 즉 3월 3일로 계산됩니다.
- 3월 1일의 한 달 전은 Date(2023, 2-1, 31), 2월 1일로 잘 계산됩니다. 
월간 지표이지만 일이 중요한 경우 (ex. 여행 중인 유저 수 추이 같은 지표가 말일이 기준이 되는 경우)가 추후에 생길 수도 있을 것 같아 굳이 1일로 날짜를 조정하지 않았었는데, setMonth를 할 때 오동작이 발생할 수 있다는 것을 간과하였습니다.
> [Hotfix] 말일 setMonth 관련 오동작 (to develop)

- app/src/@shared/ui-kit/Button/DashedButton.tsx
- app/src/@shared/ui-kit/Button/index.ts
- app/src/Calculator/components/CalculatorInput/CalculatorInputContent.tsx
- app/src/Calculator/components/CalculatorInput/CalculatorInputHeader.tsx
- app/src/Calculator/components/CalculatorInput/index.tsx
- app/src/Calculator/components/CalculatorInputContentCardView/index.tsx
- app/src/Calculator/components/CalculatorInputContentTableView/index.tsx
불편하다는 제보가 들어와 과제추가 버튼을 아랫쪽에 하나 더 만들었습니다
- close #430
> [Feat] Calculator 과제추가 버튼 추가

- app/src/Profile/dashboard-contents/General/DailyActivities/index.tsx
- app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
- app/src/Profile/dashboard-contents/General/atoms/dailyActivityErrorAtom.ts
이론상 잔디 무한로딩이 생길 수 있어 atom으로 에러상태를 추가했습니다
잔디카드(세부내용카드 X)에는 로딩상태가 없던데 의도된건지 모르겠어서 놔뒀습니다.
지금은 로딩, 에러 상태 둘 다 잔디는 비어있고(잔디 그리드는 남아있고 색깔만 비어있음)
세부내용카드에 로딩, 에러가 나게 구현되어있습니다
수정) 로딩 이슈로 남겨놓은걸 지금 봤네요. 따로 작업하시는걸로 알겠습니다!
- close #433
> [Fix] 잔디 무한로딩 버그

- app/src/@shared/ui-kit/Writable/WritableNum.tsx
- app/src/Calculator/components/CalculatorBasicInfoInputGroup/index.tsx
- app/src/Calculator/constants/levelRecords.ts
- app/src/Calculator/hooks/useSubjectList.ts
계산기 input + 레벨 버그
#440 이슈 참고
썩 내키지는 않지만 레퍼런스를 찾아봐도 지금의 현상을 깔끔하게 고칠만한 로직을 찾지 못해 제가 생각하는 가장 깔끔한 방법으로 고쳤습니다
아래의 사항 고려
input 버그
1. input을 text로 고치면 깔끔하게 해결되지만 step을 사용하지 못함 -> 타입 number 유지
2. value가 0일 때 숫자를 입력하면 숫자 앞에 0이 유지되는 현상이 있음(0일 때 1을 입력하면 1이 아닌 01로 표기됨) -> value를 파싱하는 함수 추가해서 이제 값을 지우면 0이 아닌 빈 문자열로 표기
3. xx.0x 숫자를 입력할 때 소숫점 아래 0이 사라져서 숫자 입력을 못하는 현상 -> parseFloat 사용
레벨 버그
현재 레벨 테이블이 30까지 있어서 30보다 높아지면 30으로 유지되어야하는데 0으로 초기화되서 다시 계산되는 현상 확인
- max 상수값을 만들고 계산 hook에서 max 레벨이 유지되도록 변경
- close #440
> [Hotfix] 계산기 input 버그
