42Statistics/42Stat-Frontend

app/.eslintrc.json
app/package.json
app/pnpm-lock.yaml
app/src/App.tsx
app/src/guards/AuthGuard.tsx
app/src/layouts/DashboardLayout.tsx
app/src/main.tsx
app/src/pages/404.tsx
app/src/pages/About.tsx
app/src/pages/Error.tsx
app/src/pages/Login.tsx
app/src/pages/Profile.tsx
app/src/pages/Settings.tsx
app/src/pages/Total.tsx
app/src/stores/useAuthStore.ts

PR 연습 삼아 올려봅니다 ㅎㅎ
이런 식으로 Routing 하려 합니다. 
파일이나 layout이 그리 다양하지 않아서 App.tsx에 일단 몰아서 작성했습니다. (이후 lazyImport 등 생각하면 수정될 수도 있어요)
jaham님 원래 레포 보다가 Outlet이라는 좋은 기능을 알게 되었네요 👍 
zustand를 이용하여 로그인 여부나 현재 로그인한 유저 정보를 저장해보려 합니다 ㅎㅎ

feat: :sparkles: routes basic layout

---

app/codegen.ts

https://the-guild.dev/graphql/scalars/docs/quick-start
- close #40
custom scalar 로 인해 codegen 에서 문제가 생길 줄 모르고 있었네요 ㅋㅋ;
앞으로 custom scalar 사용 시 공유드리도록 하겠습니다.

feat: :sparkles: DateTime, URL scalar 추가

---

app/src/__generated__/gql.ts
app/src/pages/ProfileEvaluationPage/contents/AverageDuration.tsx
app/src/pages/ProfileEvaluationPage/contents/AverageFeedbackLength.tsx
app/src/pages/ProfileEvaluationPage/contents/AverageFinalMark.tsx
app/src/pages/ProfileEvaluationPage/contents/CurrMonthCnt.tsx
app/src/pages/ProfileEvaluationPage/contents/MonthlyEvalCnt.tsx
app/src/pages/ProfileEvaluationPage/contents/index.ts
app/src/pages/ProfileEvaluationPage/hooks/dashboardContents.ts
app/src/pages/ProfileEvaluationPage/hooks/useProfileEvaluationPage.ts

feat: :sparkles: 프로필 페이지 평가탭 제작 (로그 제외)

---

app/src/pages/EvaluationLogSearchPage/EvaluationLogSearchPage.tsx
app/src/pages/EvaluationLogSearchPage/contents/EvalSearchBoard.tsx
app/src/pages/ProfileEvaluationPage/contents/AverageDuration.tsx
app/src/pages/ProfileEvaluationPage/contents/AverageFeedbackLength.tsx
app/src/pages/ProfileEvaluationPage/contents/AverageFinalMark.tsx
app/src/pages/ProfileEvaluationPage/contents/DestinyUsers.tsx
app/src/pages/ProfileEvaluationPage/contents/Difficulty.tsx
app/src/pages/ProfileEvaluationPage/contents/MonthlyEvalCnt.tsx
app/src/pages/ProfileEvaluationPage/contents/TotalEvalCnt.tsx

기존 스키마랑 달라진부분 반영해서 pnpm compile오류 안나게만 살짝씩들 고쳤습니다.

refactor: :recycle: 바뀐 gql schema에 따라 쿼리 조정

---

app/src/pages/StatPage/contents/AverageCircleDurations.tsx
app/src/pages/StatPage/hooks/useStatPageDashboard.ts

refactor: :recycle: N서클 통과 기간 내용과 로직 수정

---

app/src/components/common/Loader.tsx
app/src/components/common/SegmentedControl.tsx
app/src/components/elements/AppLogoTitle.tsx
app/src/components/elements/Footer/AboveTabletFooter.tsx
app/src/components/elements/Header/MobileHeader.tsx
app/src/components/elements/NavBar/DesktopNavBar.tsx
app/src/components/elements/NavBar/NavItem.tsx
app/src/components/elements/NavBar/TabItem.tsx
app/src/components/elements/NavBar/TabletNavBar.tsx
app/src/components/elements/NavBar/TabletNavItem.tsx
app/src/components/elements/UserSearchBar/AboveTabletUserSearchBar.tsx
app/src/components/elements/UserSearchBar/MobileUserSearchBar.tsx
app/src/components/layouts/MainLayout/DesktopMainLayout.tsx
app/src/components/templates/Dashboard/DashboardItemWrapper.tsx
app/src/components/templates/DashboardSkeleton/DashboardSkeletonItem.tsx
app/src/pages/EvalLogSearchPage/EvalLogItem.tsx
app/src/pages/EvalLogSearchPage/EvalLogSearchPage.tsx
app/src/pages/HomePage/HomePage.tsx
app/src/pages/ProfileEvalTab/contents/LatestFeedback.tsx
app/src/styles/global.tsx

- **예쁘다 ...**
- 기존 디자인의 background랑 카드 대비가 약간 안 어울렸다. 
-  NavBar를 가르는 선이 약간 조잡하다. (이견 있을 수 있음)
- 뉴모피즘이 UX 상 모호해서 방해된다는 의견이 있다. -> 개인적으로 사용해본 결과 뉴모피즘을 버튼마다 사용하거나 과하게 만든 경우 방해된다. 과하게 쓰지만 않으면 42 내 서비스니까 실험적으로 충분히 도입해볼만 하다. 
- box-shadow를 이용한 거라서 다크 테마를 만들 수가 없다. -> 이건 맞는 말이다. 단점이다. 
- 뉴모피즘은 box-shadow 사이즈가 크기 때문에 기존 다른 요소와의 배치에서 조금 더 멀어져야 한다. -> 부분적으로 맞는 말이다. 그래서 이번 커밋에서 마진이 필요하다고 생각되는 지점에 줘봤다.  
디자인 관련하여 의견 있으시면 반영하겠습니다!
https://github.com/42Statistics/42Stat-Frontend/assets/61629480/d4d38dce-e41c-4fcc-9b47-41ad79905e5b
기존 버전

feat: 💄 Neumorphism

---

app/src/pages/HomePage/contents/ActiveUserCountRecords.tsx
app/src/pages/HomePage/contents/BlackholedPercentage.tsx
app/src/pages/HomePage/contents/MemberPercentage.tsx
app/src/pages/HomePage/contents/UserCountPerLevels.tsx
app/src/pages/ProfileEvalTab/contents/LatestComment.tsx
app/src/pages/ProfileEvalTab/contents/LatestFeedback.tsx
app/src/pages/ProfileEvalTab/contents/index.ts
app/src/pages/ProfileEvalTab/hooks/profileEvalTabDashboardContents.ts

✨ [Feature] 2023-06-09 회의에 따른 자구 수정

---

app/public/down-arrow.svg
app/src/components/common/Select.tsx
app/src/components/common/index.ts
app/src/pages/EvalLogSearchPage/EvalLogSearchModal.tsx
app/src/pages/EvalLogSearchPage/EvalLogSearchPage.tsx
app/src/pages/EvalLogSearchPage/EvalLogSearchTitle.tsx

- Select 제작
- 평가로그 검색기 오래된 순
- 검색결과
- close #91

✨ [Feature] 평가로그 검색기 오래된 순, 검색결과

---

app/src/components/elements/SearchBar/TabletAndAbove/TabletAndAboveSearchResult/ProjectSearchItem.tsx
app/src/components/elements/SearchBar/TabletAndAbove/TabletAndAboveSearchResult/ProjectSearchList.tsx
app/src/components/elements/SearchBar/TabletAndAbove/TabletAndAboveSearchResult/UserSearchItem.tsx
app/src/components/elements/SearchBar/TabletAndAbove/TabletAndAboveSearchResult/UserSearchList.tsx
app/src/components/elements/SearchBar/TabletAndAbove/TabletAndAboveSearchResult/UserSearchResult.tsx
app/src/components/elements/SearchBar/TabletAndAbove/TabletAndAboveSearchResult/index.tsx

💄 [Design] search result 호버 시 효과

---

app/src/EvalLogSearch/index.tsx

🐛 fix: 무한 스크롤 threshold 0.1

---

app/src/@core/components/Spotlight/SpotlightResult.tsx
app/src/@core/components/Spotlight/index.tsx

🐛 [BugFix] Spotlight 길이 제한, 흰색 네모 등 버그 수정

---

app/src/@core/components/Spotlight/SpotlightListItem.tsx
app/src/@core/components/Spotlight/SpotlightResult.tsx
app/src/@core/components/Spotlight/SpotlightSearchBar.tsx
app/src/@core/components/Spotlight/index.tsx
app/src/@core/styles/defaultTheme.tsx

🐛 [BugFix] Spotlight 첫 요소에 가짜 focus

---

app/src/@core/layouts/LandingLayout/index.tsx
app/src/FtOAuthRedirect/index.tsx
app/src/Landing/index.tsx

🐛 [BugFix] LandingLayout 공통으로 Center 추가

---

app/src/@core/providers/ApolloProvider.tsx

#204 문제의 원인은,
결국 apollo link 를 통해 비동기 처리를 적절히 할 수 없기 때문에 생기는 문제라고 판단했습니다.
조사해보니 urql (다른 graphql client) 이나, axios interceptor 같은 경우는 이런 기능을 지원하도록 되어 있기 때문에 처리가 가능했구요.
일단 401 interceptor 가 불필요하게 component 안에 있어서, 그것을 분리하니 해결은 됐습니다만,
왜 됐는지는 알 수 없는 상황입니다.
추후 client 를 교체하거나, 이 부분 관련해서 무언가 middleware 하나를 만드는게 장기적인 해결 방법으로 보입니다. 
401 interceptor 를 component 밖으로 분리
- close #204

🐛 fix: 401 interceptor 를 ApolloClient contructor 에 직접 전달하도록 변경

---

app/src/@core/components/Modal/ReLoginDialog.tsx
app/src/@core/components/NavBar/Desktop/DesktopNavItem.tsx
app/src/@core/components/NavBar/Mobile(TabBar)/TabItem.tsx
app/src/@core/components/NavBar/Tablet/TabletNavItem.tsx
app/src/@core/components/Spotlight/SpotlightListItem.tsx
app/src/@shared/ui-kit/Tab/Tab.tsx
app/src/@shared/utils/compareDateDiff.ts
app/src/Error/404.tsx
app/src/Leaderboard/components/Leaderboard/LeaderboardListItem.tsx
app/src/Leaderboard/index.tsx
app/src/Profile/dashboard-contents/General/LogtimeRecord.tsx
app/src/Profile/dashboard-contents/Versus/Rankings.tsx
app/src/Profile/index.tsx

Link와 navigate를 구분해서 사용해야 합니다. 
명확한 차이점으로, 
Link는 우클릭 시 새 탭에서 열기가 되지만, navigate는 그렇지 않습니다. 
a 태그와  button 태그를 명확히 구분합시다. 
- close #211

🐛 fix: link, navigate의 사용처 구분

---

app/src/Home/dashboard-contents/Eval/EvalCountRecord.tsx
app/src/Home/dashboard-contents/Team/TeamCloseRecord.tsx
app/src/Home/dashboard-contents/User/AliveUserCountRecords.tsx
app/src/Home/dashboard-contents/User/BlackholedCountRecord.tsx
app/src/Profile/dashboard-contents/Eval/CountRecord.tsx
app/src/Profile/dashboard-contents/General/LogtimeRecord.tsx

💄 design: chart forecast

---

app/package.json
app/pnpm-lock.yaml
app/src/@core/components/NavBar/Tablet/TabletNavDrawer/index.tsx
app/src/@core/components/SearchBarShapeButton/index.tsx
app/src/@core/layouts/MainLayout/index.tsx
app/src/@shared/utils/keyboard.ts

✨ feat: Mac 이외의 사용자는 단축키 Mac -> Ctrl

---

app/src/Setting/constants/feedbackUrl.ts
app/src/Setting/index.tsx
app/src/Setting/sections/FeedbackSection/index.tsx

✨ feat: 서비스 피드백

---

app/src/@core/providers/ApolloProvider.tsx

> 잠정적 해결책입니다. 
- refresh token, access token 둘 다 없을 때는 재로그인 모달이 켜지지 않도록 조건을 추가하였습니다. 
- 대부분의 경우 잘 되지만, 한 가지 애매한 지점이 **만료 상태에서 새로고침을 했을 때**입니다. 이 경우, AuthGuard false 조건에 걸려 LandingPage로 리다이렉션되지만, refresh token, access token이 있긴 있기 때문에 LandingPage에서 재로그인 모달이 뜹니다. 
- close #243

🚧 fix: 400 Interceptor 조건 분기

---

app/src/FtOAuthRequest/index.tsx

🐛 fix: /auth/ft/request로 직접 접근할 수 있는 버그

---

app/src/@core/atoms/isReLoginDialogOpenAtom.ts
app/src/@core/atoms/reLoginDialogInfoAtom.ts
app/src/@core/components/Modal/ReLoginDialog.tsx
app/src/@core/providers/ApolloProvider.tsx
app/src/@core/providers/ModalProvider.tsx
app/src/FtOAuthRedirect/index.tsx

🐛 [BugFix] Response Error Dialog 처리 관련

---

app/index.html

🔍 chore: google analytics tag

---

app/src/@core/styles/global.tsx
app/src/@shared/components/EvalLogList/EvalLogListItem.tsx
app/src/@shared/components/EvalLogList/EvalLogListItemTitle.tsx
app/src/@shared/ui-kit/Text/Text.tsx
app/src/Team/components/MoulinetteEvalLogListItem/MoulinetteEvalLogListItemTitle.tsx
app/src/Team/index.tsx

fix(design): 평가로그 내 긴 텍스트 영역 workd-break all

---

app/src/Home/components/MyInfo/index.tsx
app/src/Profile/components/UserProfile/index.tsx

fix(design): MyInfo, UserProfile min height

---

app/src/EvalLogSearch/components/EvalLogSearchContent.tsx

fix(EvalLogSearchContent): missing footer

---

app/src/@core/components/NavBar/Mobile(TabBar)/index.tsx

[Design] 탭 바 위로 올리기

---

app/src/Profile/dashboard-contents/General/PreferredTime.tsx

feat(PreferredTime): 200시간 이상 출석왕

---

app/index.html

fix(ga): prod 이외의 환경에서 GA가 적용되는 버그

---

app/src/Leaderboard/pages/ExpIncrement/components/LeaderboardExpIncrementResult.tsx

fix(Leaderboard): 경험치 증가량 단위 오기

---

app/src/@shared/types/fragments/TEAM_USER_PREVIEW_FIELDS.ts
app/src/Team/index.tsx
app/src/Team/utils/teamUserCompareFn.ts

팀장(isLeader) > 트라이 횟수(occurrence) > 이름(login) 순

[Feature] 팀원 정렬 함수 추가

---

app/src/Leaderboard/pages/Comment/components/LeaderboardCommentResult.tsx
app/src/Leaderboard/pages/Comment/index.tsx

누적의 경우에만 **평가 횟수가 20회 미만인 유저는 집계되지 않아요.** 내용이 등장합니다.

[Feat] 코멘트 길이 랭킹 기간별 추가

---

app/src/Leaderboard/pages/Comment/components/LeaderboardCommentResult.tsx

기존 dateTemplate이 없다가 새로 추가하면서 이걸 빼먹었네요...

[Hotfix] 코멘트 길이 랭킹 handlePageNumberChange 보완 (dev)

---

app/src/Calculator/atoms/currentOpenSpotlightIndexAtom.ts
app/src/Calculator/components/CalculatorInputContentTableView/index.tsx

블랙홀 페이지 오류 hotfix
- 페이지 처음 들어올 때 focus되는 현상
- desktop에서 subject 1개일때 삭제되는 현상

[Hotfix] calculator(dev)

---

app/src/Calculator/atoms/currentOpenSpotlightIndexAtom.ts
app/src/Calculator/components/CalculatorInputContentTableView/index.tsx

블랙홀 페이지 오류 hotfix
- 페이지 처음 들어올 때 focus되는 현상
- desktop에서 subject 1개일때 삭제되는 현상

[Hotfix] calculator

---

app/src/Team/index.tsx

- 커밋에 있는 코드가 Prod에서는 안 터지는데, Local에서는 터지더라구요...?
- data로 받은 객체를 변경하는 일은 하지 말아야겠습니다.

[Fix] Team 페이지 내 잘못된 sort 사용

---

app/.storybook/preview.tsx
app/src/@core/components/NavProfile/Desktop/index.tsx
app/src/@core/components/NavProfile/Tablet/index.tsx
app/src/@core/components/Spotlight/SpotlightUserListItem.tsx
app/src/@shared/components/DashboardContentView/Number/NumberVersus.tsx
app/src/@shared/components/DashboardContentView/Rank/UserRankListItem.tsx
app/src/@shared/ui-kit/Avatar/Avatar.tsx
app/src/@shared/ui-kit/Avatar/AvatarInitials.tsx
app/src/@shared/utils/pickColorFromString.ts
app/src/Leaderboard/components/Leaderboard/LeaderboardListItem.tsx
app/src/Profile/components/UserProfile/index.tsx
app/src/Profile/dashboard-contents/Versus/AverageCommentLength.tsx
app/src/Profile/dashboard-contents/Versus/AverageFinalMark.tsx
app/src/Profile/dashboard-contents/Versus/DayFromBeginAt.tsx
app/src/Profile/dashboard-contents/Versus/Level.tsx
app/src/Profile/dashboard-contents/Versus/TotalEvalCount.tsx
app/src/Profile/dashboard-contents/Versus/TotalLogtime.tsx

이니셜을 표기해주는 Avatar를 제작했습니다
- 로딩, 사진 에러일 때 이니셜 표기되는 아바타를 불러오도록 했습니다 (내 정보 header 제외)
- 랜덤한 색상을 string 기준으로 정하게 만들었습니다 (아예 랜덤한 색상을 고르면 유저마다 색을 고유하게 어떻게 지정해줄 지 감이 안잡히네요 ㅋ..)
- 색을 결정할 때 밝기, 범위도 정할 수 있게 하였습니다. light모드일 때 어두운 색상, dark모드일 때 밝은 색상을 가져오게 설정했어요.
- 이니셜은 intraId 앞 두글자로 했습니다. 혹시나 실제 이름을 기준으로 하고싶으면 api에 추가해야될 것 같아요.
- fontSize도 width처럼 size별로 지정해줬습니다
- close #307

[Feat] AvatarInitials 제작

---

app/src/Calculator/atoms/subjectListAtom.ts

calculator subjectListAtom 초기값 설정
- emptySubjectList에 빈 subject가 아닌 빈 배열 자체로 설정되있던 문제 해결
- close #369

[Fix] subjectListAtom 초기값 수정

---

app/src/Leaderboard/hooks/useGetSelectKey.ts

[Fix] (Leaderboard) select key promo & coalition 정보 추가

---

app/src/@shared/assets/icon/triangle-down.svg
app/src/@shared/ui-kit/Select/FormSelect.tsx
app/src/@shared/ui-kit/Select/SelectItem.tsx

[Fix] 다크모드 svg fill error

---

.github/workflows/s3-ci.yml

[CI] prod 배포 조건 published로 변경

---

.github/workflows/build-test.yml

- #363 해결하면서 이 스크립트도 docker-compose를 이용하는 것으로 변경하겠습니다. 
- close #373

[CI] pr 시 build test

---

app/src/@shared/components/Chart/LineChart.tsx

ApexCharts 라이브러리 상 #239 의 문제가 있었는데, 바뀐 건 없지만 일단 해제해보고 문제 재발생하면 고치겠습니다. 
- Ref. #239, #240

[Feat] LineChart animation 재활성화

---

.github/workflows/build-test.yml
.github/workflows/s3-ci-dev.yml
.github/workflows/s3-ci.yml
Dockerfile.dev
Dockerfile.prod
docker-compose.dev.yml
docker-compose.prod.yml
entry.dev.sh
entry.prod.sh

Github Actions에서 빌드할 때 Docker Compose를 사용하도록 변경하였습니다. 
build test는 테스트 완료하였는데, 배포 자동화는 develop에 올려봐야 압니다. 
최대한 될 것 같이 만들어놓긴 했습니다. 
- close #363 
- Ref. #56

[CI] Github Actions에서 Docker Compose 사용

---

app/src/@core/styles/Theme.d.ts
app/src/@core/styles/darkTheme.tsx
app/src/@core/styles/lightTheme.tsx
app/src/Home/dashboard-contents/User/BlackholedCountPerCircle.tsx
app/src/Home/dashboard-contents/User/UserRate.tsx

UserRate 도넛 차트 변경
- 차트 도넛으로 변경
- total 색상 mono.black으로 고정 (서클별 블랙홀 유저 카운트 차트도 같이 적용)
- 블랙홀 색 chart.blackhole로 지정
- close #391

[Feat] UserRate 도넛 차트 변경

---

.github/workflows/s3-ci-dev.yml
.github/workflows/s3-ci.yml

index.html이 cloudfrond에서 캐싱되지 않도록, max-age=0으로 설정하였습니다. 
- 로컬에서 직접 커맨드 쳐서 테스트해봤는데 잘 되더라구요. 
- 이제 invalidation을 하지 않으셔도 됩니다. 
- close #388

[CI] index.html max-age=0

---

app/src/Profile/dashboard-contents/General/DailyActivities/ColorLegendList/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/DailyActivitiesResult.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/DailyActivityTable.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/DailyActivityTableData.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/atoms/currentDateScrollLeftAtom.ts

처음(latestActivityDate)에만 움직이도록 수정
- component의 width를 구해서 month 차이만큼 scroll 이동하게 수정
- scroll관련 atom 삭제
- close #409

[Fix] dailyActivity scroll 수정

---

app/src/@core/components/NavBar/Mobile/index.tsx
app/src/@core/components/NavBar/shared/NavMenu.tsx
app/src/@core/components/NavProfile/Mobile/index.tsx

[Fix] NavMenu Mobile일 때 설정 탭 위로 올림

---

app/src/@core/styles/lightTheme.tsx

[Design] Change main layout theme-color to #fff

---

app/src/@shared/components/Chart/hooks/useDefaultOptions.ts

zoom보다 pan을 더 잘 사용할 것 같아서 변경합니다.

[Feat] Change toolbar auto-selected to pan

---

app/src/@shared/ui-kit/Select/SelectTrigger.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/YearSelect/index.tsx

[Hotfix] YearSelect width 줄이기 (to develop)

---

app/src/@shared/ui-kit/Select/SelectTrigger.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/DailyActivityTableData.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/YearSelect/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivityDetail/DailyActivityTimeline/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
app/src/Profile/dashboard-contents/General/atoms/selectedDailyActivityAtom.ts

selectedDailyActivityAtom을 초기화하지 않아서 생긴 버그
atom을 초기화할 필요는 없는 것 같고 atom에 login을 추가해서 useContext의 login이랑 일치하지 않으면 카드를 로딩으로 뜨게 바꿨습니다!

[HotFix] dailyActivity 다른 사람 활동이 보이는 버그

---

app/src/Profile/dashboard-contents/General/DailyActivities/DailyActivityTableData.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivityDetail/DailyActivityTimeline/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
app/src/Profile/dashboard-contents/General/atoms/selectedDailyActivityAtom.ts

[HotFix] dailyActivity 다른 사람 활동이 보이는 버그 (dev)

---

app/src/@shared/ui-kit/Select/SelectTrigger.tsx
app/src/@shared/utils/firstDayInPreviousMonth.ts
app/src/@shared/utils/injectEmptyMonth.ts
app/src/Profile/dashboard-contents/General/DailyActivities/DailyActivityTableData.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/YearSelect/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivities/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivityDetail/DailyActivityTimeline/index.tsx
app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
app/src/Profile/dashboard-contents/General/atoms/selectedDailyActivityAtom.ts

커밋이 꼬여서 develop -> main 머지 한번 하겠습니다.
v0.4.0 이후 Hotfix 이외에 기능 개발한 것이 없어 가능할 듯합니다.

develop -> main 

---

app/src/@shared/ui-kit/Writable/WritableNum.tsx
app/src/Calculator/components/CalculatorBasicInfoInputGroup/index.tsx
app/src/Calculator/constants/levelRecords.ts
app/src/Calculator/hooks/useSubjectList.ts

[Hotfix] 계산기 input 버그 - dev

---

app/package.json
app/src/@shared/ui-kit/Writable/WritableNum.tsx
app/src/Calculator/components/CalculatorBasicInfoInputGroup/index.tsx
app/src/Calculator/constants/levelRecords.ts
app/src/Calculator/hooks/useSubjectList.ts
app/src/Leaderboard/pages/Comment/components/LeaderboardCommentResult.tsx
app/src/Leaderboard/pages/EvalCount/components/LeaderboardEvalCountResult.tsx
app/src/Leaderboard/pages/ExpIncrement/components/LeaderboardExpIncrementResult.tsx
app/src/Leaderboard/pages/Score/components/LeaderboardScoreResult.tsx

[Hotfix] 랭킹 페이지네이션 코알리숑 쿼리 추가 - dev

---

app/src/Calculator/components/CalculatorInput/CalculatorInputContent.tsx
app/src/Calculator/components/CalculatorInputContentTableView/index.tsx

https://42born2code.slack.com/archives/CU6MTFBNH/p1723870684914129?thread_ts=1718014690.780789&cid=CU6MTFBNH

fix: calculator score input elemenet value 를 handler 에서만 관리하게 수정
